name: applecta
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  video_player: ^2.10.0
  http: ^1.4.0
  palette_generator: ^0.3.3+7
  flutter_html: ^3.0.0
  lottie: ^3.3.1
  collection: ^1.19.1
  barcode_scan2: ^4.5.1
  image_picker: ^1.0.4
  flutter_local_notifications: ^19.3.0
  file_picker: ^10.2.0
  path_provider: ^2.1.5
  timezone: ^0.10.1
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/sfondo-light.png
    - assets/images/sfondo-dark.png
    - assets/videos/sfondogradient_dark.mp4
    - assets/videos/sfondogradient_light.mp4
    - assets/images/logo.png
    - assets/images/logo-small.png
    - assets/images/bookclub.png
    - assets/images/empty-shelf.png
    - assets/images/tavola-obb-dark.png
    - assets/images/tavola-obb-light.png
    - assets/images/tavola-sfide-dark.png
    - assets/images/tavola-sfide-light.png
  
  fonts:
    - family: Roobert
      fonts:
        - asset: fonts/Roobert.ttf
    - family: LibreCaslonCondensed
      fonts:
        - asset: fonts/LibreCaslonCondensed-Regular.ttf
          weight: 400
        - asset: fonts/LibreCaslonCondensed-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/LibreCaslonCondensed-Medium.ttf
          weight: 500
        - asset: fonts/LibreCaslonCondensed-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/LibreCaslonCondensed-SemiBold.ttf
          weight: 600
        - asset: fonts/LibreCaslonCondensed-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/LibreCaslonCondensed-Bold.ttf
          weight: 700
        - asset: fonts/LibreCaslonCondensed-BoldItalic.ttf
          weight: 700
          style: italic

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  
  # Per Android normale
  android_gravity: center
  
  # Per Android 12+
  android_12:
    color: "#FFFFFF"
    image: assets/images/logo.png
    icon_background_color: "#FFFFFF"
  
  # Per iOS
  ios_content_mode: center
  
  android: true
  ios: true
  web: false